homework_45/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include("webapp.urls")),
                  path('accounts/', include("accounts.urls")),

              ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from .views.projects import ProjectListView, ProjectCreateView, ProjectDetailView, ProjectDelete, ProjectUpdate, \
    ProjectMembersAdd, ProjectMembersDelete
from webapp.views import CreateTask, ListTaskView, DeleteTask, UpdateTask

app_name = 'webapp'

urlpatterns = [
    path('', ProjectListView.as_view(), name="index"),
    path('to_do_lists/add/', CreateTask.as_view(), name="create_task"),
    path('detail/<int:pk>/', ListTaskView.as_view(), name="detail_view"),
    path('delete/<int:pk>/', DeleteTask.as_view(), name="delete_description"),
    path('to_do_lists/<int:pk>/update', UpdateTask.as_view(), name="update"),

    # path('projects/', ProjectListView.as_view(), name='project_view'),
    path('projects/add/', ProjectCreateView.as_view(), name='project_create'),
    path('projectdetailview/<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('project/delete/<int:pk>/', ProjectDelete.as_view(), name='project_delete'),
    path('projects/update/<int:pk>/', ProjectUpdate.as_view(), name='project_update'),

    path('project/<int:pk>/member/add', ProjectMembersAdd.as_view(), name='members_add'),
    path('project/<int:pk>/member/delete', ProjectMembersDelete.as_view(), name='members_delete')
]

webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

PROJECT_MANAGER = "project_manager"
TEAM_LEAD = "team_lead"
DEVELOPER = "developer"
ROLE_CHOIСES = [
    (PROJECT_MANAGER, "Project Manager"),
    (TEAM_LEAD, "Team Lead"),
    (DEVELOPER, "Developer")
]


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now=True, verbose_name='Created at')
    updated_at = models.DateTimeField(auto_now_add=True, verbose_name='Updated at')

    class Meta:
        abstract = True


class Status(models.Model):
    status = models.CharField(max_length=40, verbose_name='Status')

    def __str__(self):
        return f"{self.status}"

    class Meta:
        db_table = 'status'
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'


class Type(models.Model):
    type = models.CharField(max_length=40, verbose_name='Type')

    def __str__(self):
        return f"{self.type}"

    class Meta:
        db_table = 'type'
        verbose_name = 'Тип'
        verbose_name_plural = 'Типы'


class ToDoList(BaseModel):
    summary = models.CharField(max_length=15, null=True, blank=False, verbose_name="Name")
    description = models.TextField(max_length=3000, null=True, blank=True, verbose_name='Description')
    status = models.ForeignKey('webapp.Status', on_delete=models.PROTECT, related_name='status_tasks',
                               verbose_name='Status')
    types = models.ManyToManyField('webapp.Type', related_name='type_tasks', blank=True, verbose_name='Types')
    project = models.ForeignKey('webapp.Project', related_name='project_tasks', default=1, on_delete=models.CASCADE,
                                verbose_name='Project')

    def __str__(self):
        return f"{self.id}. {self.summary}: {self.status}"

    def get_absolute_url(self):
        return reverse('webapp:detail_view', kwargs={'pk': self.pk})

    class Meta:
        db_table = 'tasks'
        verbose_name = 'Описание'
        verbose_name_plural = 'Описания'


class Project(models.Model):
    data_begin = models.DateField(max_length=20, verbose_name='Date begin')
    data_end = models.DateField(max_length=20, null=True, blank=True, verbose_name='Date end')
    title = models.CharField(max_length=20, verbose_name="Name")
    description = models.TextField(max_length=2000, verbose_name="Description")
    is_deleted = models.BooleanField(default=False)
    members = models.ManyToManyField(User, related_name='projects',
                                     verbose_name='Project')

    def __str__(self):
        return f"{self.id}. {self.title}: {self.description}"

    def get_absolute_url(self):
        return reverse('webapp:project_detail', kwargs={'pk': self.pk})

    class Meta:
        db_table = 'projects'
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'


class ProjectUser(models.Model):
    project = models.ForeignKey('webapp.Project', on_delete=models.CASCADE, related_name='projectusers',
                                verbose_name='Project')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='userprojects', verbose_name='User')
    role = models.CharField(max_length=250, choices=ROLE_CHOIСES, default=PROJECT_MANAGER, verbose_name='Role')

    class Meta:
        db_table = 'projectuser'
        unique_together = ('project', 'user')

    def __str__(self):
        return f"{self.user}. {self.project.title} - {self.role}"

webapp/views/projects.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import Q
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.http import urlencode
from django.views.generic import DetailView, ListView, CreateView, DeleteView, UpdateView

from webapp.forms import SearchForm, ProjectForm, MemberAddForm, ListForm
from webapp.models import Project, ProjectUser, PROJECT_MANAGER, ToDoList


class ProjectListView(ListView):
    model = Project
    context_object_name = 'projects'
    ordering = 'title'
    template_name = 'projects/project_view.html'

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        if self.search_value:
            return Project.objects.filter(
                Q(title__icontains=self.search_value) | Q(description__icontains=self.search_value))
        return Project.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            query = urlencode({'search': self.search_value})
            context['query'] = query
            context['search'] = self.search_value
        return context

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data.get('search')


class ProjectDetailView(DetailView):
    template_name = "projects/project_detailview.html"
    model = Project
    context_object_name = "project"


class ProjectCreateView(PermissionRequiredMixin, CreateView):
    permission_required = "webapp.add_project"
    model = Project
    form_class = ProjectForm
    template_name = 'projects/project_create.html'


class ProjectDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'webapp.delete_project'
    template_name = 'projects/project_delete.html'
    model = Project
    context_object_name = 'project'
    success_url = reverse_lazy('webapp:index')

    def get_queryset(self):
        return super().get_queryset().filter(is_deleted=False)


class ProjectUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = "webapp.change_project"
    template_name = "projects/project_update.html"
    model = Project
    context_object_name = 'project'
    form_class = ProjectForm

    def get_success_url(self):
        return reverse('webapp:project_detail', kwargs={'pk': self.object.pk})


class SearchView(ListView):
    model = Project
    form_class = SearchForm
    context_object_name = 'project'
    tasks = []

    def get_queryset(self):
        form = self.form_class(self.request.GET)
        if form.is_valid():
            return Project.objects.filter(title__icontains=form.cleaned_data['title'])
        return Project.objects.all()


class ProjectMembersAdd(PermissionRequiredMixin, CreateView):
    permission_required = "webapp.add_projectuser"
    model = Project
    template_name = 'projects/members_add.html'
    form_class = MemberAddForm

    def post(self, request, *args, **kwargs):
        project = self.get_object()
        form = self.get_form()
        if form.is_valid():
            pru = form.save(commit=False)
            pru.project = project
            pru.save()
            return redirect('webapp:index', pk=project.pk)
        else:
            return self.form_invalid(form)

    def get(self, request, *args, **kwargs):
        project = self.get_object()
        form = MemberAddForm(project_id=project.id)
        return render(request, self.template_name, {'form': form, 'project': project})

    def has_permission(self):
        project = self.get_object()
        user_id = self.request.POST.get('user_id')
        if ProjectUser.objects.filter(user=self.request.user, project=project).exists():
            member = ProjectUser.objects.get(user=self.request.user, project=project)
            return super().has_permission() and user_id != self.request.user.id and member.role
        else:
            return False


class ProjectMembersDelete(PermissionRequiredMixin, DeleteView):
    permission_required = "webapp.delete_projectuser"
    model = Project
    success_url = reverse_lazy('webapp:index')

    def post(self, request, *args, **kwargs):
        project = self.get_object()
        user_id = request.POST.get('user_id')
        project.member.remove(user_id)
        return redirect('webapp:detail_view', pk=project.pk)

    def has_permission(self):
        project = self.get_object()
        user_id = self.request.POST.get('user_id')
        if ProjectUser.objects.filter(user=self.request.user, project=project).exists():
            member = ProjectUser.objects.get(user=self.request.user, project=project)
            return super().has_permission() and int(
                user_id) != self.request.user.id and member.role == PROJECT_MANAGER
        else:
            return False

templates/projects/members_add.html
{% extends 'base.html' %}
{% block title %}New member of the project{% endblock %}
{% block nav %} {% endblock %}
{% block content %}
    <h1>Add a new member!</h1>
    <form action="{% url "webapp:members_add" project.pk%}" method="post">
    {% include 'partial/form.html' with button_text="Create" %}
    </form>
{% endblock %}

templates/projects/project_create.html
{% extends "base.html" %}
{% block title %} Creat Project{% endblock %}
{% block content %}

    <h1>Create Projects</h1>
    <form action=" " method="post">
        {% include "partial/form.html" with button_text="Create" %}
        <a href="{% url "webapp:index" %}" class="btn btn-primary">BACK</a>
    </form>
    <br/>
{% endblock %}

templates/projects/project_delete.html
{% extends "base.html" %}
{% block title %} Удаление статьи {% endblock %}
{% block content %}

    <form action=" " method="POST">
        {% csrf_token %}
        <h2>Are you sure you want to delete the article {{ project.title }}?</h2>
        <button type="submit" class="btn btn-primary">YES</button>
        <a href="{% url 'webapp:project_detail' project.pk %}" class="btn btn-primary">NO</a>
    </form>
{% endblock %}

templates/projects/project_detailview.html
{% extends "base.html" %}
{% block title %} Detail List{% endblock %}
{% block nav %}
    {% if  request.user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:project_create' %}">Create project</a>
        </li>
    {% endif %}
    {% if  perms.webapp.add_projectuser %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:members_add' project.pk %}"> Add Member</a>
        </li>
    {% endif %}
    {% if perms.webapp.add_task %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:create_task' %}">Create task</a>
        </li>
    {% endif %}
{% endblock %}
{% block content %}
    <br>
    <div class="card text-center">
        <div class="card-header">
            {{ project.get_status_display }}
        </div>
        <div class="card-body">
            <h5 class="card-title">{{ project.title|upper }}</h5>
            <p class="card-text">{{ project.description }}</p>
            {% if perms.webapp.delete_project %}
                <a href="{% url 'webapp:project_delete' project.pk %}" class="btn btn-primary">DELETE</a>
            {% endif %}
            {% if perms.webapp.change_project %}
                <a href="{% url 'webapp:project_update' project.pk %}" class="btn btn-primary">EDIT</a>
            {% endif %}
            <a href="{% url 'webapp:index' %}" class="btn btn-primary">BACK</a>
        </div>
        <div class="card-body">
            <h6>Tasks:</h6>
            {% for to_do_list in project.project_tasks.all %}
                <br>
                <div class="card p-2 " style="max-width: 400px;">
                    <div>
                        <p class="card-title ">{{ to_do_list.summary }}</p>
                        {% if perms.webapp.delete_task %}
                            <a href="{% url "webapp:delete_description" to_do_list.pk %}" class="btn btn-danger"
                               style="float: right">
                                Delete</a>
                        {% endif %}
                        {% if perms.webapp.delete_task %}
                            <a href="{% url "webapp:detail_view" to_do_list.pk %}" class="btn btn-info"
                               style="float: right">
                                Detail view</a>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
        <h5>Members:</h5>
        {% for p in project.projectusers.all %}
            <br>
            <div class="card" style="max-width: 400px;">
                <div class="card-body">
                    <h5 class="card-title">Name:
                        <a href="{% url 'accounts:user_profile' p.user.pk %}">{% firstof p.user.first_name p.user.last_name p.user.username %}</a>
                    </h5>
                    <p class="card-text">Role: {{ p.get_role_display }}</p>
                    {% if perms.webapp.delete_projectuser %}
                        <form action="{% url 'webapp:members_delete' project.pk %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="user_id" value="{{ p.user.pk }}">
                            <button type="submit" class="btn-danger">Delete</button>
                        </form>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
        <div class="card-footer text-muted">
            {{ project.data_begin }}
        </div>
    </div>
{% endblock %}

templates/projects/project_update.html
{% extends "base.html" %}
{% block title %} Update Project{% endblock %}
{% block content %}

    <h1>Update Projects</h1>
    <form action=" " method="post">
        {% include "partial/form.html" with button_text="Update" %}
        <a href="{% url "webapp:project_detail" project.pk %}" class="btn btn-primary">BACK</a>
    </form>
    <br/>
{% endblock %}

templates/projects/project_view.html
{% extends "base.html" %}
{% block title %} Projects{% endblock %}
{% load static %}
{% block nav %}
    {% if  user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:project_create' %}">Create project</a>
        </li>
    {% endif %}
    {% if perms.webapp.add_task %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:create_task' %}">Create task</a>
        </li>
    {% endif %}

{% endblock %}
{% block content %}
    <div class="mt-3">{% include 'partial/simple_search.html' %} </div>

    {% include 'partial/project_list_partial.html' %}

{% endblock %}