accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import RegisterView, ProfileView, UserList, ChangeProfileView, ChangePasswordView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('registration/', RegisterView.as_view(), name='registration'),
    path('<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/list', UserList.as_view(), name='profile_list'),

    path('<int:pk>/change/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
]

homework_45/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include("webapp.urls")),
                  path('accounts/', include("accounts.urls")),

              ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from .views.projects import ProjectListView, ProjectCreateView, ProjectDetailView, ProjectDelete, ProjectUpdate, \
    ProjectMembersAdd, ProjectMembersDelete
from webapp.views import CreateTask, ListTaskView, DeleteTask, UpdateTask

app_name = 'webapp'

urlpatterns = [
    path('', ProjectListView.as_view(), name="index"),
    path('to_do_lists/add/', CreateTask.as_view(), name="create_task"),
    path('detail/<int:pk>/', ListTaskView.as_view(), name="detail_view"),
    path('delete/<int:pk>/', DeleteTask.as_view(), name="delete_description"),
    path('to_do_lists/<int:pk>/update', UpdateTask.as_view(), name="update"),

    # path('projects/', ProjectListView.as_view(), name='project_view'),
    path('projects/add/', ProjectCreateView.as_view(), name='project_create'),
    path('projectdetailview/<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('project/delete/<int:pk>/', ProjectDelete.as_view(), name='project_delete'),
    path('projects/update/<int:pk>/', ProjectUpdate.as_view(), name='project_update'),

    path('project/<int:pk>/member/add', ProjectMembersAdd.as_view(), name='members_add'),
    path('project/<int:pk>/member/delete', ProjectMembersDelete.as_view(), name='members_delete')
]

accounts/models.py
from django.contrib.auth import get_user_model
from django.db import models


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE,
                                verbose_name='User', related_name='profile')
    avatar = models.ImageField(upload_to='avatars', null=True, blank=True, verbose_name='Avatar')
    about_user = models.CharField(max_length=200, null=True, blank=True, verbose_name='About user')
    git = models.URLField(null=True, blank=True, verbose_name='GIT')

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

webapp/views/base_view.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import TemplateView, ListView


class DetailView(TemplateView):
    context_key = 'to_do_list'
    model = None
    key_kwarg = 'pk'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_key] = self.get_object()
        return context

    def get_object(self):
        pk = self.kwargs.get(self.key_kwarg)
        return get_object_or_404(self.model, pk=pk)


# class ListView(ListView):
#     model = None
#     context_key = 'to_do_list'
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context[self.context_key] = self.model.objects.all()
#         return context
#
#     def get_objects(self):
#         return self.model.objects.all()


class FormView(View):
    form_class = None
    template_name = None
    redirect_url = ''

    def get_redirect_url(self):
        return redirect(self.redirect_url)

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = self.get_context_data(form=form)
        return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        return self.form_invalid(form)

    def form_valid(self, form):
        return self.get_redirect_url()

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        return render(self.request, self.template_name, context=context)

    def get_context_data(self, **kwargs):
        return kwargs

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <title> {% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url "webapp:index" %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% block nav %}
                {% endblock %}
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link menu-right" href="{% url "accounts:logout" %}">Get out</a>
                    </li>
                    <li class="menu-right nav-link">
                        <p>Hello, <a href="{% url 'accounts:profile' request.user.pk %}"
                                     style="text-decoration:none; color: red"> {{ user.username }}</a></p>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "accounts:login" %}?next={{ request.get_full_path }}">Enter</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "accounts:registration" %}?next={{ request.get_full_path }}">Registration</a>
                    </li>
                {% endif %}
                {% if perms.accounts.view_profile %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "accounts:profile_list" %}">Users</a>
                    </li>
            {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% block content %}
    {% endblock %}

</div>
</body>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
</html>