homework_45/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include("webapp.urls")),
                  path('accounts/', include("accounts.urls")),

              ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from .views.projects import ProjectListView, ProjectCreateView, ProjectDetailView, ProjectDelete, ProjectUpdate, \
    ProjectMembersAdd, ProjectMembersDelete
from webapp.views import CreateTask, ListTaskView, DeleteTask, UpdateTask

app_name = 'webapp'

urlpatterns = [
    path('', ProjectListView.as_view(), name="index"),
    path('to_do_lists/add/', CreateTask.as_view(), name="create_task"),
    path('detail/<int:pk>/', ListTaskView.as_view(), name="detail_view"),
    path('delete/<int:pk>/', DeleteTask.as_view(), name="delete_description"),
    path('to_do_lists/<int:pk>/update', UpdateTask.as_view(), name="update"),

    # path('projects/', ProjectListView.as_view(), name='project_view'),
    path('projects/add/', ProjectCreateView.as_view(), name='project_create'),
    path('projectdetailview/<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('project/delete/<int:pk>/', ProjectDelete.as_view(), name='project_delete'),
    path('projects/update/<int:pk>/', ProjectUpdate.as_view(), name='project_update'),

    path('project/<int:pk>/member/add', ProjectMembersAdd.as_view(), name='members_add'),
    path('project/<int:pk>/member/delete', ProjectMembersDelete.as_view(), name='members_delete')
]

webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

PROJECT_MANAGER = "project_manager"
TEAM_LEAD = "team_lead"
DEVELOPER = "developer"
ROLE_CHOIСES = [
    (PROJECT_MANAGER, "Project Manager"),
    (TEAM_LEAD, "Team Lead"),
    (DEVELOPER, "Developer")
]


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now=True, verbose_name='Created at')
    updated_at = models.DateTimeField(auto_now_add=True, verbose_name='Updated at')

    class Meta:
        abstract = True


class Status(models.Model):
    status = models.CharField(max_length=40, verbose_name='Status')

    def __str__(self):
        return f"{self.status}"

    class Meta:
        db_table = 'status'
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'


class Type(models.Model):
    type = models.CharField(max_length=40, verbose_name='Type')

    def __str__(self):
        return f"{self.type}"

    class Meta:
        db_table = 'type'
        verbose_name = 'Тип'
        verbose_name_plural = 'Типы'


class ToDoList(BaseModel):
    summary = models.CharField(max_length=15, null=True, blank=False, verbose_name="Name")
    description = models.TextField(max_length=3000, null=True, blank=True, verbose_name='Description')
    status = models.ForeignKey('webapp.Status', on_delete=models.PROTECT, related_name='status_tasks',
                               verbose_name='Status')
    types = models.ManyToManyField('webapp.Type', related_name='type_tasks', blank=True, verbose_name='Types')
    project = models.ForeignKey('webapp.Project', related_name='project_tasks', default=1, on_delete=models.CASCADE,
                                verbose_name='Project')

    def __str__(self):
        return f"{self.id}. {self.summary}: {self.status}"

    def get_absolute_url(self):
        return reverse('webapp:detail_view', kwargs={'pk': self.pk})

    class Meta:
        db_table = 'tasks'
        verbose_name = 'Описание'
        verbose_name_plural = 'Описания'


class Project(models.Model):
    data_begin = models.DateField(max_length=20, verbose_name='Date begin')
    data_end = models.DateField(max_length=20, null=True, blank=True, verbose_name='Date end')
    title = models.CharField(max_length=20, verbose_name="Name")
    description = models.TextField(max_length=2000, verbose_name="Description")
    is_deleted = models.BooleanField(default=False)
    members = models.ManyToManyField(User, related_name='projects',
                                     verbose_name='Project')

    def __str__(self):
        return f"{self.id}. {self.title}: {self.description}"

    def get_absolute_url(self):
        return reverse('webapp:project_detail', kwargs={'pk': self.pk})

    class Meta:
        db_table = 'projects'
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'


class ProjectUser(models.Model):
    project = models.ForeignKey('webapp.Project', on_delete=models.CASCADE, related_name='projectusers',
                                verbose_name='Project')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='userprojects', verbose_name='User')
    role = models.CharField(max_length=250, choices=ROLE_CHOIСES, default=PROJECT_MANAGER, verbose_name='Role')

    class Meta:
        db_table = 'projectuser'
        unique_together = ('project', 'user')

    def __str__(self):
        return f"{self.user}. {self.project.title} - {self.role}"

webapp/views/tasks.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import redirect

from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView

from webapp.views.base_view import DetailView
from webapp.forms import ListForm
from webapp.models import ToDoList


# class IndexView(ListView):
#     model = ToDoList
#     template_name = 'tasks/index.html'
#     context_object_name = 'to_do_list'
#     ordering = '-updated_at'
#     paginate_by = 10
#     paginate_orphans = 1
#
#     def get(self, request, *args, **kwargs):
#         self.form = self.get_search_form()
#         self.search_value = self.get_search_value()
#         return super().get(request, *args, **kwargs)
#
#     def get_queryset(self):
#         if self.search_value:
#             return ToDoList.objects.filter(
#                 Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value))
#         return ToDoList.objects.all()
#
#     def get_context_data(self, *, object_list=None, **kwargs):
#         context = super().get_context_data(object_list=object_list, **kwargs)
#         context['form'] = self.form
#         if self.search_value:
#             query = urlencode({'search': self.search_value})
#             context['query'] = query
#             context['search'] = self.search_value
#         return context
#
#     def get_search_form(self):
#         return SearchForm(self.request.GET)
#
#     def get_search_value(self):
#         if self.form.is_valid():
#             return self.form.cleaned_data.get('search')


class ListTaskView(DetailView):
    template_name = "tasks/ditail_view.html"
    model = ToDoList


class CreateTask(PermissionRequiredMixin, CreateView):
    permission_required = "webapp.add_task"
    form_class = ListForm
    template_name = 'tasks/create.html'
    model = ToDoList

    def get_success_url(self):
        return reverse("webapp:detail_view", kwargs={"pk": self.object.pk})


class DeleteTask(PermissionRequiredMixin, DeleteView):
    permission_required = "webapp.delete_task"
    template_name = "tasks/delete.html"
    model = ToDoList
    context_object_name = 'to_do_list'
    success_url = reverse_lazy('webapp:index')

    def get_success_url(self):
        return reverse("webapp:project_detail", kwargs={"pk": self.object.project.pk})


class UpdateTask(PermissionRequiredMixin, UpdateView):
    permission_required = "webapp.update_task"
    form_class = ListForm
    template_name = "tasks/update.html"
    model = ToDoList
    context_object_name = 'to_do_list'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)
    def get_success_url(self):
        return reverse('webapp:detail_view', kwargs={'pk': self.object.project.pk})

templates/tasks/create.html
{% extends "base.html" %}
{% block title %} Creat List{% endblock %}
{% block content %}

    <h1>Create To Do List</h1>
    <form action=" " method="post">
        {% include "partial/form.html" with button_text="Create" %}
        <a href="{% url "webapp:index" %}" class="btn btn-primary">BACK</a>
    </form>
    <br/>
{% endblock %}

templates/tasks/delete.html
{% extends "base.html" %}
{% block title %} Delete task {% endblock %}
{% block content %}

<form action=" " method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete the task {{  to_do_list.summary }}?</h2>
    <button type="submit" class="btn btn-primary">YES</button>
<a href="{% url "webapp:detail_view" to_do_list.pk %}" class="btn btn-primary">NO</a>
</form>
{% endblock %}

templates/tasks/ditail_view.html
{% extends "base.html" %}
{% block title %} Detail List{% endblock %}
{% block nav %}
    {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:create_task' %}">Create task</a>
        </li>
    {% endif %}
{% endblock %}
{% block content %}
    <br>
    <div class="card text-center">
        <div class="card-header">
            {{ to_do_list.get_status_display }}
        </div>
        <div class="card-body">
            <h5 class="card-title">{{ to_do_list.summary|upper }}</h5>
            <p class="card-text">{{ to_do_list.description }}</p>
            <p class="card-text">Status: {{ to_do_list.status }}</p>
            <p>Type: {% for type in to_do_list.types.all %}{{ type.type }}{% if not forloop.last %},
            {% endif %}{% endfor %}</p>
            {% if  perms.webapp.delete_task %}
                <a href="{% url 'webapp:delete_description' to_do_list.pk %}" class="btn btn-primary">DELETE</a>
            {% endif %}
                <a href="{% url 'webapp:update' to_do_list.pk %}" class="btn btn-primary">EDIT</a>
            <a href="{% url 'webapp:index' %}" class="btn btn-primary">BACK</a>
        </div>
        <div class="card-footer text-muted">
            {{ to_do_list.created_at }}
        </div>
    </div>
{% endblock %}

templates/tasks/index.html
{##}
{##}
{#{% extends 'base.html' %}#}
{#{% block title %}Main{% endblock %}#}
{#{% block content %}#}
{#    <h1><a href="{% url "project_view" project.pk %}">Projects View</a></h1>#}
{#    <h1><a href="{% url "webapp:index" %}">Tasks View</a></h1>#}
{#{% endblock %}#}


{% extends "base.html" %}
{% block title %} To do list{% endblock %}
{% load static %}
{% block nav %}
     {% if request.user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'webapp:create_task' %}">Create list</a>
    </li>
       {% endif %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'webapp:project_view' %}"> View project</a>
    </li>
{% endblock %}
{% block content %}
    {% include 'partial/simple_search.html' %}
    <h1>To do list</h1>
    {% for list in  to_do_list %}
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{ list.summary }}</h5>
                <p class="card-text">{{ list.description }}</p>
                {% if request.user.is_authenticated %}
                <a href="{% url 'webapp:detail_view' list.pk  %}" class="btn btn-primary">MORE</a>
                       {% endif %}
            </div>
        </div>
        <br>
    {% endfor %}
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}

templates/tasks/update.html
{% extends "base.html" %}
{% block title %}Update Task{% endblock %}
{% block content %}

    <h1>Update Task</h1>
    <form method="post" action=" ">
        {% include "partial/form.html" with button_text="Edit" %}

        <a href="{% url "webapp:detail_view" to_do_list.pk %}" class="btn btn-primary">BACK</a>
    </form>
{% endblock %}